Header header

arm_master_comm input_command

arm_joint_state L1
arm_joint_state L2
arm_joint_state L3
arm_joint_state L4
arm_joint_state L5
arm_joint_state L6
arm_joint_state L7
arm_joint_state L8

arm_joint_state R1
arm_joint_state R2
arm_joint_state R3
arm_joint_state R4
arm_joint_state R5
arm_joint_state R6
arm_joint_state R7
arm_joint_state R8

arm_dynamixel_state DXL1
arm_dynamixel_state DXL2
arm_dynamixel_state DXL3
arm_dynamixel_state DXL4